include 'prepare-ssh.yml'

stages:
  - publish-code

publish-code-job:
  stage: publish-code
  extends:
    - .prepare_ssh
  only:
    - main
  script:
    - git remote set-url origin $GITHUB_URL 
    - git push origin HEAD:main
