include: '.prepare-ssh.yml'

stages:
  - publish-code

publish-code-job:
  stage: publish-code
  tags:
    - "shell"
  extends:
    - .prepare_ssh
  only:
    - main
  script:
    - git remote set-url origin $GITHUB_URL 
    - git push -u origin HEAD:main
